# Generated by Django 2.2.5 on 2019-09-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190924_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='buglogstructure',
            old_name='subject',
            new_name='steps',
        ),
        migrations.RenameField(
            model_name='buglogstructure',
            old_name='yourName',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='buglogstructure',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buglogstructure',
            name='message',
        ),
        migrations.AddField(
            model_name='buglogstructure',
            name='feature',
            field=models.CharField(choices=[('Camera', 'Theia/Camera'), ('Tstat Reg', 'Tstat Registration')], default=('Camera', 'Theia/Camera'), max_length=2),
        ),
        migrations.AddField(
            model_name='buglogstructure',
            name='result',
            field=models.TextField(default='Enter a descriptive result here', max_length=500),
        ),
        migrations.AlterField(
            model_name='buglogstructure',
            name='device',
            field=models.CharField(choices=[('6s', 'Iphone 6s 20140928'), ('Mini', 'Ipad Mini 20142706')], default=('6s', 'Iphone 6s 20140928'), max_length=2),
        ),
    ]
