# Generated by Django 2.2.5 on 2019-09-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buglogstructure',
            name='device',
            field=models.CharField(choices=[('6s', 'Iphone 6s 20140928'), ('Mini', 'Ipad Mini 20142706')], default=('6s', 'Iphone 6s 20140928'), max_length=2),
        ),
        migrations.AlterField(
            model_name='buglogstructure',
            name='feature',
            field=models.CharField(choices=[('Camera', 'Theia/Camera'), ('Tstat Reg', 'Tstat Registration')], default=('Camera', 'Theia/Camera'), max_length=2),
        ),
    ]
