# Generated by Django 3.0 on 2019-12-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, default=0)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Camera', models.PositiveIntegerField(blank=True, default=0)),
                ('Tstat', models.PositiveIntegerField(blank=True, default=0)),
                ('Sensors', models.PositiveIntegerField(blank=True, default=0)),
                ('Ls', models.PositiveIntegerField(blank=True, default=0)),
                ('Eco_plus', models.PositiveIntegerField(blank=True, default=0)),
                ('Iris', models.PositiveIntegerField(blank=True, default=0)),
                ('total', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
