# Generated by Django 3.0 on 2019-12-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='product',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='Android',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='CAMERA',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='ECO_PLUS',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='SENSORS',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='SWITCH',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='TSTAT',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='iOS',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
