# Generated by Django 3.0 on 2019-12-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BashSessionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('6s', 'Iphone 6s 20140928'), ('Mini', 'Ipad Mini 20142706')], default=('6s', 'Iphone 6s 20140928'), max_length=50)),
                ('feature', models.CharField(choices=[('Camera', 'Theia/Camera'), ('Tstat Reg', 'Tstat Registration')], default=('Camera', 'Theia/Camera'), max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='buglogstructure',
            name='result',
            field=models.TextField(default='Actual:\n\nExpected:\n', max_length=500),
        ),
        migrations.AlterField(
            model_name='buglogstructure',
            name='steps',
            field=models.TextField(default='1. \n2.\n3.\n4.', max_length=350),
        ),
    ]
